# Generated by Django 5.2.5 on 2025-10-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_aboutus_privacypolicy_termsandconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_ceo_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_hr_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_project_leader_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_team_lead_approved',
            field=models.BooleanField(default=False),
        ),
    ]
