# Generated by Django 5.2.5 on 2025-10-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_leave_is_ceo_approved_leave_is_hr_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_ceo_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_hr_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_project_leader_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_team_lead_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
