# Generated by Django 5.2.5 on 2025-09-26 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_officelocation_qrsession_attendance_qr_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_logo', models.FileField(upload_to='project_logo/')),
                ('project_name', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('priority', models.CharField(verbose_name=100)),
                ('project_value', models.CharField(blank=True, null=True, verbose_name=100)),
                ('total_working_hours', models.CharField(max_length=50)),
                ('extra_time', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField()),
                ('attachment', models.FileField(upload_to='Project_attachment/')),
            ],
        ),
        migrations.CreateModel(
            name='QR_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='DEFAULT_CODE', max_length=255)),
                ('latitudes', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='qrsession',
            name='office',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='qr_session',
        ),
        migrations.AddField(
            model_name='attendance',
            name='punch_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='user_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='leave_attachments/'),
        ),
        migrations.AddField(
            model_name='leave',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_app.employeedetail'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_app.project'),
        ),
        migrations.CreateModel(
            name='ProjectMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_leader', models.JSONField()),
                ('project_manager', models.JSONField()),
                ('tags', models.JSONField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.project')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='qrsession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.qr_session'),
        ),
        migrations.DeleteModel(
            name='OfficeLocation',
        ),
        migrations.DeleteModel(
            name='QRSession',
        ),
    ]
