# Generated by Django 5.2.5 on 2025-10-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_leave_is_ceo_rejected_leave_is_hr_rejected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='selfie',
        ),
        migrations.AddField(
            model_name='attendance',
            name='in_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_selfies/in'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='out_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_selfies/out/'),
        ),
    ]
