# Generated by Django 5.2.5 on 2025-09-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_project_qr_session_remove_qrsession_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
