# Generated by Django 5.2.5 on 2025-10-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_employeedetail_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='emp_exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='emp_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='face_encoding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
