# Generated by Django 5.2.5 on 2025-10-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
