# Generated by Django 5.2.5 on 2025-10-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_holiday_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
