# Generated by Django 5.2.5 on 2025-10-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_notificationlog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='reated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
