# Generated by Django 5.2.5 on 2025-10-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_leave_reated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='reated_at',
            new_name='created_at',
        ),
    ]
