# Generated by Django 5.2.5 on 2025-10-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_rename_reated_at_leave_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
