# Generated by Django 5.2.5 on 2025-10-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reason_for_rejection',
            field=models.TextField(blank=True, null=True),
        ),
    ]
