# Generated by Django 5.2.5 on 2025-10-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_project_reason_for_rejection'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
